# Generated by Django 4.0.5 on 2022-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='c_image',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='category',
            name='c_status',
            field=models.BooleanField(default=False),
        ),
    ]
