# Generated by Django 4.0.5 on 2022-06-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_category_options_alter_commentproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=255)),
                ('contactlastname', models.CharField(max_length=255)),
                ('contactemail', models.EmailField(max_length=254)),
                ('contactdescription', models.TextField(max_length=255)),
            ],
        ),
    ]
